[workspace]
resolver = "2"
members = [
    "fly-http",
]

[workspace.package]
version = "0.1.0"
license = "MIT"
authors = ["Project Developers"]
edition = "2024"
repository = "TBD"
rust-version = "1.89.0"

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen = "0.45.1"
wstd = "0.5.4"

[profile.release]
opt-level = "s"
debug = 1
